config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }
           
  root 'main#get_location'
  
  get '/map_page' => 'main#map_page'
  get '/first' => 'main#first'
  post '/first' => 'main#first'
  get '/second' => 'main#second'
  get '/write' =>'main#write'
  get '/read/:post_id' => 'main#read'
  get '/test' => 'main#test'
  get '/profile/:user_id'=>'main#profile'
  get '/maptest' => 'main#maptest'
  post '/write_ok' => 'main#write_ok'
  post '/position_ok' => 'main#position_ok'
  post '/comment_reg' =>'main#comment_reg'
  get '/get_location' => 'main#get_location'
  get '/follow_request/:user_id' => 'main#follow_request' 
  get '/follow_cancel/:user_id' => 'main#follow_cancel'
  
  post '/post_delete' => 'main#post_delete'
  post '/post_update' => 'main#post_update'
  post '/post_update_ok' => 'main#post_update_ok'
  
  post '/back_photo_reg' => 'main#back_photo_reg'
  post '/profile_photo_reg' => 'main#profile_photo_reg'
  post '/profile_introduce_reg' => 'main#profile_introduce_reg'
  post '/read_message' => 'main#read_message'
  post '/send_message' => 'main#send_message'
  post '/send_message_ok' => 'main#send_message_ok'
  
  
  
  
  

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include Math
  
  
  def index
  end

  def signin
  end

  def signup
  end

  def map_page
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end

  end

  def position_ok
    @user = User.find(current_user.id)
    
    @user.latitude = params[:latitude]
    @user.longitude = params[:longitude]
    @user.save
    current_user.latitude= @user.latitude
    current_user.longitude=@user.longitude
    redirect_to '/'
  end


  def login
  end
  
  
  def first
    
      @temp = User.new
      
      if user_signed_in?
        @cur_user = User.find(current_user.id)
        if params[:latitude] == nil || params[:longitude] == nil then
          @temp.latitude = 37.592574
          @temp.longitude = 127.024742
        else
          @temp.latitude = current_user.latitude
          @temp.longitude = current_user.longitude
        end
      else
        @cur_user = User.new
        if params[:latitude] == nil || params[:longitude] == nil then
          @temp.latitude = 37.592574
          @temp.longitude = 127.024742
        else
          @temp.latitude = params[:latitude]
          @temp.longitude = params[:longitude]
        end
      end
      
        
      @users = User.all
        
      @results = Array.new
      @myLat = @temp.latitude
      @myLong = @temp.longitude
      
      
      @users.each do |u| 
        if u.latitude != 0.0 && u.longitude != 0.0 then
         
          distance = calDistance2(@myLat.to_f, @myLong.to_f, u.latitude.to_f, u.longitude.to_f) * 1000
          
          if 500.0 > distance
            @results << u
          end
        end
        
      end
      
      if @results != nil 
        @results.sort! { |a, b|  b.star_score <=> a.star_score }
      end
      
      
      @photo_addr = Array.new(3)
      
      for i in 0..2
        
        if @results.at(i) == nil
          temp_user = User.new
          temp_user.name = ""
          temp_user.profile_photo_addr = "default.png"
          @photo_addr[i] = "default.png"
          @results << temp_user
        elsif @results.at(i).profile_photo_addr.to_s == ""
          @photo_addr[i] = "default.png"
        else
          @photo_addr[i] = @results.at(i).profile_photo_addr.to_s
        end
        
        
      end
      
      
      
  end
  
  def <=>(other)
    self.star_score <=> other.star_score
  end



  
  
  def get_star_score(user)
    
    @myPosts = Post.where(writer: user.id)
    temp_total_star = 0
    temp_total_count = 0
    @myPosts.each do |mp|
      temp_total_count = temp_total_count + mp.comment_cnt
      temp_total_star = temp_total_star + mp.total_star
    end
    
    if temp_total_count == 0
      return 0.0
    else
      return temp_total_star.to_f / temp_total_count.to_f    
    end

      
  end
  
  
  
  def get_location
    
  end
  
  

  def second
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
    @user = User.all
    
    
    
    radius = params[:radius]
    chk = params[:chk]    #체크박스 파라미터

    @posts = Array.new    #Post 배열 생성
    for i in 1..6

      @temp = Post.where(category: chk[i.to_s])  #where절로 가져온 배열 temp에 넣기
      @temp.each do |t|
        @posts << t                 #temp에 있는 각 원소들 @posts에 차곡차곡 넣기
      end

    end
 
    u = User.find(current_user.id)
    @myLat = u.latitude.to_f
    @myLong =u.longitude.to_f

    @results = Array.new
    @posts.each do |p|
      distance = calDistance2(@myLat, @myLong, p.lat.to_f, p.lng.to_f)* 1000
      
      if radius.to_f > distance
        @results << p

      end
      
    end


  end

  def calDistance(myLat, myLong, destLat, destLong)
        theta = myLong - destLong
        dist = Math.sin(deg2rad(myLat))*Math.sin(deg2rad(destLat)) + Math.cos(deg2rad(myLat)) * Math.cos(deg2rad(destLat)) * Math.cos(deg2rad(theta))

        dist = Math.acos(dist)
        dist = rad2deg(dist)
        dist = dist * 60 * 1.1515

        dist = dist*1609.344
      return dist
  end

  def calDistance2(lat1, lon1, lat2, lon2)
    p = 0.017453292519943295
    a = 0.5-Math.cos((lat2 - lat1)*p)/2 + Math.cos(lat1*p)*Math.cos(lat2*p)*(1 - Math.cos((lon2 - lon1)*p))/2
    return 12742 * Math.asin(Math.sqrt(a))
  end


  # def deg2rad(deg)
  #   return (deg*Math::PI/180.0)
  # end
  # def rad2deg(rad)
  #   return (rad * 180 / Math::PI)
  # end
  
  def deg2rad(deg)
    return (deg*Math::PI/180.0)
  end
  def rad2deg(rad)
    return (rad * 180.0 / Math::PI)
  end
  
  

  def third
  end

  def temp
  end

  def read
    @post = Post.find(params[:post_id])
    @user = User.find(@post.writer)
    if @user.profile_photo_addr.to_s == ""
      @user_photo = "/default.png"
    else
      @user_photo = @user.profile_photo_addr
    end
    @comments = Comment.where(post_id: @post.id)
  end
  
  def comment_reg
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    @comment.writer = params[:writer]
    @comment.content = params[:content]
    @comment.star_score = params[:rating]
    @comment.save
    
    
    
    #여기 해당 post 별점 평균 계산하는거 추가해야함
    @post = Post.find(@comment.post_id)
    
    @post.total_star = @post.total_star + @comment.star_score
    @post.comment_cnt = @post.comment_cnt + 1
    
    @post.avg_star_score = @post.total_star.to_f / @post.comment_cnt.to_f
    @post.save
    
    @user = User.find(@post.writer)
    @user.star_score = get_star_score(@user)
    @user.save
    
    redirect_to '/read/'+@comment.post_id.to_s
  end
  
  
  def send_message
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
    
    @user = User.find(params[:user_id])
  end

  def send_message_ok
    @message = Message.new
    @message.sender_id = current_user.id
    @message.receiver_id = params[:receiver_id]
    @message.message = params[:content]
    @message.save
    
    redirect_to '/profile/'+params[:receiver_id]
  end
  
  def read_message
    @results = Message.where(receiver_id: current_user.id)
    
  end
  

  def profile
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
    
    @user = User.find(params[:user_id])
    @results = Post.where(writer: params[:user_id])
    
    if @user.back_photo_addr.to_s == ""
      @back_photo = "/noodles.png"
    else
      @back_photo = @user.back_photo_addr
    end
    p @user.back_photo_addr
    
    if @user.profile_photo_addr.to_s == ""
      @profile_photo = "/sushi.png"
    else
      @profile_photo = @user.profile_photo_addr
    end
    
    @user_following = Follow.where(following_id: params[:user_id])
    @user_follower = Follow.where(follower_id: params[:user_id])
    if current_user !=nil
      @my_follow_list = Follow.where(following_id: current_user.id);
      @isFollow = false;
      @my_follow_list.each do |f|
        if f.follower_id == params[:user_id]
          @isFollow = true;
          break;
        end
      end
    end
    
    # @isFollow = @my_follow_list.follower_id.include?(params[:user_id]);
    
  end

  def follow_request
    
    @follow = Follow.new()
    @follow.following_id = current_user.id
    @follow.follower_id = params[:user_id]
    @follow.save
    redirect_to '/profile/'+params[:user_id]
  end
  
  
  def follow_cancel
    
    @follow = Follow.where(following_id: current_user.id, follower_id: params[:user_id])
    
    @follow.first.delete
    redirect_to '/profile/'+params[:user_id]
  end
  
  def post_update
    @post = Post.find(params[:post_id])
    if @post.food_photo.to_s == ""
      @food_photo = "default.png"
    else
      @food_photo = @post.food_photo
    end
    @user = User.find(@post.writer)
    
  end
  
  def post_update_ok
    
    @p = Post.find(params[:post_id])
    
    @p.food_photo = params[:food_photo]
    @p.content = params[:content]
    @p.total_price = params[:total_price]
    @p.people_num = params[:people_num]
    @p.final_date = params[:final_date]
    @p.lat = params[:post_lat]
    @p.lng = params[:post_long]
    @p.category = params[:category]
    @p.save

    redirect_to '/profile/'+current_user.id.to_s
  end

  def post_delete
    @post = Post.find(params[:post_id])
    @comments = Comment.where(post_id: params[:post_id])
    
    @comments.each do |c|
      c.delete
    end
    
    
    @post.delete
    
    @user = User.find(@post.writer)
    @user.star_score = get_star_score(@user)
    @user.save
    
    redirect_to '/profile/'+current_user.id.to_s
  end
  
  
  
  
  def back_photo_reg
    
    @user = User.find(params[:user_id])
    @user.back_photo_addr = params[:photo_addr]
    @user.save
    redirect_to '/profile/'+params[:user_id]
  end
  
  def profile_photo_reg
    
    @user = User.find(params[:user_id])
    @user.profile_photo_addr = params[:photo_addr]
    @user.save
    redirect_to '/profile/'+params[:user_id]
  end
  
  def profile_introduce_reg
    @user = User.find(params[:user_id])
    @user.introduce = params[:content]
    @user.save
    redirect_to '/profile/'+params[:user_id]
  end
  
  

  def write
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
  end

  def test
    
  end
  
  def write_ok

    @p = Post.new
    @p.writer = current_user.id;
    @p.name = params[:name]
    @p.food_photo = params[:food_photo]
    @p.content = params[:content]
    @p.total_price = params[:total_price]
    @p.people_num = params[:people_num]
    @p.final_date = params[:final_date]
    @p.lat = params[:post_lat]
    @p.lng = params[:post_long]
    @p.category = params[:category]
    @p.save

    redirect_to '/'
  end  
   
  
end

app/views/main/maptest.html.erb
 <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?clientId=5uQbAffakTOIS4lajJId&submodules=geocoder"></script>
<div class="wrapper" align="center">
            <div id="map" style="width:100%;height:400px;"></div>
</div> 
<script> 
var map = new naver.maps.Map("map", {
    center: new naver.maps.LatLng(37.3595316, 127.1052133),
    zoom: 10,
    mapTypeControl: true
});

var infoWindow = new naver.maps.InfoWindow({
    anchorSkew: true
});

map.setCursor('pointer');

// search by tm128 coordinate
function searchCoordinateToAddress(latlng) {
    var tm128 = naver.maps.TransCoord.fromLatLngToTM128(latlng);

    infoWindow.close();

    naver.maps.Service.reverseGeocode({
        location: tm128,
        coordType: naver.maps.Service.CoordType.TM128
    }, function(status, response) {
        if (status === naver.maps.Service.Status.ERROR) {
            return alert('Something Wrong!');
        }

        var items = response.result.items,
            htmlAddresses = [];

        for (var i=0, ii=items.length, item, addrType; i<ii; i++) {
            item = items[i];
            addrType = item.isRoadAddress ? '[도로명 주소]' : '[지번 주소]';

            htmlAddresses.push((i+1) +'. '+ addrType +' '+ item.address);
        }

        infoWindow.setContent([
                '<div style="padding:10px;min-width:200px;line-height:150%;">',
                '<h4 style="margin-top:5px;">검색 좌표</h4><br />',
                htmlAddresses.join('<br />'),
                '</div>'
            ].join('\n'));

        infoWindow.open(map, latlng);
    });
}

// result by latlng coordinate
function searchAddressToCoordinate(address) {
    naver.maps.Service.geocode({
        address: address
    }, function(status, response) {
        if (status === naver.maps.Service.Status.ERROR) {
            return alert('Something Wrong!');
        }

        var item = response.result.items[0],
            addrType = item.isRoadAddress ? '[도로명 주소]' : '[지번 주소]',
            point = new naver.maps.Point(item.point.x, item.point.y);

        infoWindow.setContent([
                '<div style="padding:10px;min-width:200px;line-height:150%;">',
                '<h4 style="margin-top:5px;">검색 주소 : '+ response.result.userquery +'</h4><br />',
                addrType +' '+ item.address +'<br />',
                '</div>'
            ].join('\n'));


        map.setCenter(point);
        infoWindow.open(map, point);
    });
}

function initGeocoder() {
    map.addListener('click', function(e) {
        searchCoordinateToAddress(e.coord);
    });

    $('#address').on('keydown', function(e) {
        var keyCode = e.which;

        if (keyCode === 13) { // Enter Key
            searchAddressToCoordinate($('#address').val());
        }
    });

    $('#submit').on('click', function(e) {
        e.preventDefault();

        searchAddressToCoordinate($('#address').val());
    });

    searchAddressToCoordinate('정자동 178-1');
}

naver.maps.onJSContentLoaded = initGeocoder;
</script>

app/views/main/signup.html.erb
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
        
        
        <style>
            .title{
                 font-family:'BMJUA','배달의민족 주아',sans-serif;
                 color : #85d9f8;
            }
            .signup{
                margin-top:50px;
                font-family:'BMJUA','배달의민족 주아',sans-serif;
            }
            .btn{
                background: #85d9f8;
                color: white;
                border-radius: 0;
            }
            input[type=text] {
                height: 40px;
                width: 400px;
                -webkit-transition: all 0.30s ease-in-out;
                -moz-transition: all 0.30s ease-in-out;
                -ms-transition: all 0.30s ease-in-out;
                -o-transition: all 0.30s ease-in-out;
                outline: none;
                padding: 3px 0px 3px 3px;
                margin: 5px 1px 3px 0px;
                border: 1px solid #DDDDDD;
                border-radius: 10px;
            }
        </style>
    </head>

    <body>
        
        
        
        
        <div class="signup" align=center>
            <div class="title">
                <h1>회원가입</h1>
            </div>
            <div class="form">
                <form action="">
                    <table>
                        <tr>
                            <td>아이디<br></td>
                            <td colspan="3"><input type="text" name=""></td>
                        </tr>
                        <tr>
                            <td>비밀번호<br></td>
                            <td colspan="3"><input type="text" name="sinup[pw]" placeholder="6~10자리 영문 혼합입니다."></td>
                        </tr>
                        <tr>
                            <td>비밀번호 재확인<br></td>
                            <td colspan="3"><input type="text" name="sinup[re-pw]"></td>
                        </tr>
                        <tr>
                            <td>이름</td>
                            <td colspan="3"><input type="text" name="sinup[name]"></td>
                        </tr>
                        <tr>
                            <td>생년월일</td>
                            <td colspan="3"><input type="text" name="sinup[rrn]" placeholder="ex) 960921"></td>
                        </tr>
                        <tr>
                            <td>본인 확인 이메일</td>
                            <td colspan="3"><input type="text" name="sinup[email]"></td>
                        </tr>
                        <tr>
                            <td>휴대전화</td>
                            <td colspan="3"><input type="text" name="sinup[phone]"placeholder="ex) 01064897714"></td>
                        </tr>
                        <tr>
                            <td>성별</td>
                            <td colspan="10" align="left">
                                <div class="form-group col-md-4">
                                    <select id="inputState" class="form-control" width:100px;>
                                        <option>남자</option>
                                        <option>여자</option>
                                    </select>
                                </div>
                            </td>
                        </tr>

                        <tr>
                            <td align="center" colspan="3">
                                <a href="#" button type="button" class="btn">가입신청</button>
                            </td>
                        </tr>
                        <tr>
                            <td align="center" colspan="3"><br><br><br><br>
                                <%- if controller_name != 'sessions' %><%= link_to "Log in", new_session_path(resource_name) %><br /><% end -%>
                            </td>
                        </tr>

                    </table>
                </form>
            </div>
    </body>
</html>

app/views/main/temp_forgetpw.html.erb
<h2>Forgot your password?</h2>

<%= simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Send me reset password instructions" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/main/temp_signup.html.erb
<h2>Sign up</h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email,
                required: true,
                autofocus: true ,
                input_html: { autocomplete: "email" }%>
    <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>